### ISSUE TITLE
COSMOS 1050K dataset availability

### ISSUE THREAD

**Issue by DhyeyR-007** [yuhoo0302/Segment-Anything-Model-for-Medical-Images#1]
From where can I get the COSOMOS 1050K dataset? I am unable to locate it.
Thanks.

**Comment by yuhoo0302** [comment]
Hi, we have provided the links to the datasets in the readme file ([COSMOS 1050K](https://github.com/yuhoo0302/Segment-Anything-Model-for-Medical-Images?tab=readme-ov-file#cosmos-1050k-dataset)). Please find the datasets you want in the corresponding links.
