### ISSUE TITLE
matric error

### ISSUE THREAD

**Issue by tianxiaoer** [yuhoo0302/Segment-Anything-Model-for-Medical-Images#10]
你好，我用您提供的预训练模型在ISIC数据集进行了测试，在测试的时候遇到了错误，请问您知道怎么解决吗？current_imgs_p的shape是（0,1），current_matrix的shape是（0,）
![截图 2024-06-22 19-46-55](https://github.com/yuhoo0302/Segment-Anything-Model-for-Medical-Images/assets/117167954/be740c22-267c-4dd1-99f2-6e05e2c7b5f6)
![截图 2024-06-22 19-47-46](https://github.com/yuhoo0302/Segment-Anything-Model-for-Medical-Images/assets/117167954/d7721c52-0350-42b1-ae7f-ba77d00590f5)

**Comment by yuhoo0302** [comment]
shape都是0，应该是由于没通过某个设定的条件导致的
