### ISSUE TITLE
分割结果

### ISSUE THREAD

**Issue by tianxiaoer** [yuhoo0302/Segment-Anything-Model-for-Medical-Images#11]
您好，我用CVC-300和BraTS数据集在预训练模型运行，分割出来的结果是一张全黑的图，我想请加一下是什么原因造成的呢
![截图 2024-07-09 16-50-39](https://github.com/yuhoo0302/Segment-Anything-Model-for-Medical-Images/assets/117167954/74e540f9-a741-461d-91e3-0fc3483633e4)

**Comment by yuhoo0302** [comment]
看起来是数据没加载成功
