### ISSUE TITLE
Excellent work! Can you provide detailed guidance on how to use the dataset? How to organize data?

### ISSUE THREAD

**Issue by Ever-Bright-V** [yuhoo0302/Segment-Anything-Model-for-Medical-Images#12]

**Comment by yuhoo0302** [comment]
Please see the Readme file about [how to use or collect the data](https://github.com/yuhoo0302/Segment-Anything-Model-for-Medical-Images?tab=readme-ov-file#1-prepare-data-and-segmentation-information-json-files-corresponding-to-each-test-set).

If you mean how to get the COSMOS dataset, please refer to [COSMOS 1050K](https://github.com/yuhoo0302/Segment-Anything-Model-for-Medical-Images?tab=readme-ov-file#cosmos-1050k-dataset).
