### ISSUE TITLE
About GPU memory expenses

### ISSUE THREAD

**Issue by Hang3Y** [yuhoo0302/Segment-Anything-Model-for-Medical-Images#3]
I wonder how much GPU memory you are using when running train_only_box.py? Even with Batch size set to 1, it prompts for not enough GPU memory. Many Thanks! 
It would be great if you could share the GPU configuration used for training the model!

**Comment by yuhoo0302** [comment]
Hi, we used only one GPU with 24G memory. 
Batch size is related to the image size. We test images with size 448*320, the batch size can be set as 128, and the GPU memory is about 19G.
One potential solution is that you can remove the stored GT from 'npy' files (i.e., choose not to save), we save this information just for fast calculation, but it will occupy some additional memory. Besides, you can try to resize the image to a smaller size.

**Comment by Hang3Y** [comment]
Appreciate your support!

**Comment by yuhoo0302** [comment]
Hi!  We observe that the provided commands in the Readme file have some mistakes, for preparing the datasets, it should be:
/python pre_grey_rgb2D.py   --img_path  data/train_data/images    --gt_path data/train_data/labels   --checkpoint sam_vit_b_01ec64.pth 
In this way, the npz['gt'] will not occupy a large memory, the OOM problem will not appear.

**Comment by yuhoo0302** [comment]
Hi! We observe that the provided commands in the Readme file have some mistakes, for preparing the datasets, it should be:
```python
python pre_grey_rgb2D.py --img_path data/train_data/images  --gt_path data/train_data/labels  --checkpoint sam_vit_b_01ec64.pth
``` 
In this way, the npz['gt'] will not occupy a large memory, the OOM problem will not appear.
