### ISSUE TITLE
Some questions about pre_grey_rgb2D.py and pre_grey_rgb2DHuge.py

### ISSUE THREAD

**Issue by DingeF** [yuhoo0302/Segment-Anything-Model-for-Medical-Images#4]
Hi, Is the mode value filled in opposite values in pre_grey_rgb2D. py and pre_grey_rgb2DHuge. py?

**Comment by yuhoo0302** [comment]
Hi, the mode value is about the ViT sizes. In pre_grey_rgb2D. py, mode value='B', representing the ViT-B model, while in pre_grey_rgb2DHuge. py, it should be 'H', for loading the ViT-H model.
