### ISSUE TITLE
关于npz的存储字典中保存的npz_data['gts']标签问题

### ISSUE THREAD

**Issue by DBook111** [yuhoo0302/Segment-Anything-Model-for-Medical-Images#5]
你好，很荣幸能学习您的工作，我有如下疑问：
我注意到你保存的npz文件中'gts'对应的值的shape为(129, 440, 512)，其中440，512对应标签图像的宽和高。但是，这个129代表什么我不是很理解。标签图是灰度图，所以标签的形状不应该是(1, 440, 512)，如果转换为one-hot的话，我注意到你所使用的数据集分3个类，在加一个背景，shape也应该为(4, 440, 512)。所以这个129代表什么我无法理解，希望能得到您的解答。

**Comment by yuhoo0302** [comment]
您好，npz_data['gts']存储的shape应该是[n,w,h]，n是当前图像GT的类别。我们测试了提供的数据示例，发现没有您说到的这个出现shape为（129,440,512）的情况，想问一下您这边使用的具体数据是？

**Comment by DBook111** [comment]
我使用的是您提供的22_Heart数据集（标签中LeftVentricle像素值为85，LeftVentricularMyocardium像素值为170，RightVentricle像素值为255。原始图片标签为单通道。

我所说的129的具体位置位于类NpzDataset(Dataset)中，在调用__getitem__(self, index)方法的时候，
`gt2D = npz_data['gts']
gt2D = torch.tensor(gt2D).long()`
其中，这个gt2D 也就是标签的shape为([(129, 440, 512)])。
然而正如你所说的，n是当前GT的类别，所以我认为应该为([(4, 440, 512)])。

断点调试结果如图：
![image](https://github.com/yuhoo0302/Segment-Anything-Model-for-Medical-Images/assets/101385916/22a75bb7-66ba-4bc0-b305-08cde736cb77)
我将这129个通道的图片（仅包含像素0和1，我将1变为255）都可视化出来了，发现是很离散的图。。。如下图所示
![image](https://github.com/yuhoo0302/Segment-Anything-Model-for-Medical-Images/assets/101385916/b2a4ec18-a87e-42db-8906-6a59c5db3f4c)
![image](https://github.com/yuhoo0302/Segment-Anything-Model-for-Medical-Images/assets/101385916/78d4d838-3c8b-4440-a766-653e322bb6a5)

**Comment by yuhoo0302** [comment]
我觉得您可能是存gts的时候，把原始图片读进去了，可以再检查一下读取的路径（pre_grey_rgb的py代码），and可能跟我们提供的readme文件有关，我们已经更新了readme文件，您可以再试一下，谢谢！

**Comment by DBook111** [comment]
非常感谢您的解答👍，我确实在pre_grey_rgb存标签的时候把原始图片都进去了。。🤣

**Comment by DBook111** [comment]
顺便提一下，我怀疑问题3也是遭遇了和我相同的问题。。因为192和通道的时候确实显存占用非常大，显存16G的卡会爆。我在修改之后，显存只占到了3G。

**Comment by yuhoo0302** [comment]
cool! 谢谢你的提醒~祝你实验顺利！
