### ISSUE TITLE
你好，我想请教一下数据集处理的问题

### ISSUE THREAD

**Issue by CYYJL** [yuhoo0302/Segment-Anything-Model-for-Medical-Images#8]
你好，我阅读了您的文章，想在Luna16、DRIVE、ISIC 2018等数据集上进行运行和修改，但是不知道如何进行预处理和生成json文件，在此特地请教您

**Comment by yuhoo0302** [comment]
你好，数据不需要进行很复杂的预处理，生成json文件（python json库）和数据存储格式只需要符合要求即可：[prepare data](https://github.com/yuhoo0302/Segment-Anything-Model-for-Medical-Images?tab=readme-ov-file#1-prepare-data-and-segmentation-information-json-files-corresponding-to-each-test-set)
