### ISSUE TITLE
IXI Dataset - Callosum Labels

### ISSUE THREAD

**Issue by Zrrr1997** [yuhoo0302/Segment-Anything-Model-for-Medical-Images#9]
How do you obtain the callosum labels for the IXI dataset? It seems the link you provided only contains images but no labels. 

https://brain-development.org/ixi-dataset/

**Comment by yuhoo0302** [comment]
Hi, we found the labels of the IXI dataset at https://aistudio.baidu.com/aistudio/projectdetail/1993321?channelType=0&channel=0.
The authors of this project used Labelme software to annotate the callosum manually. For more details refer to the website.
